name: Flutter CI/CD

on:
  push:
    branches:
      - guillaume/deploy

  pull_request:

jobs:
  android:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'


      - name: Restore keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_GUI }}" | base64 --decode > android/upload-keystore.jks
          test -f android/upload-keystore.jks
          ls -lh android/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD_GUI }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD_GUI }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS_GUI }}" >> android/key.properties
          echo "storeFile=../upload-keystore.jks" >> android/key.properties


      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Debug key.properties
        run: |
          ls -la android
          cat android/key.properties

      - name: Build APK
        run: |
          flutter build apk \
          --release \
          --dart-define=API_URL=${{ secrets.API_URL_GUI }}

      - name: Build App Bundle
        run: |
          flutter build appbundle \
            --release \
            --dart-define=API_URL=${{ secrets.API_URL_GUI }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Artichette-Guillaume-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab