name: Flutter CI/CD

on:
  push:
    branches:
      - guillaume/deploy

  pull_request:

jobs:
  android:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: |
          flutter build apk \
          --release \
          --dart-define=API_URL=${{ secrets.API_URL_GUI }}

      - name: Build App Bundle
        run: |
          flutter build appbundle \
            --release \
            --dart-define=API_URL=${{ secrets.API_URL_GUI }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Artichette-Guillaume-APK
          path: build/app/outputs/flutter-apk/Artichette-Guillaume.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab